### ISSUE TITLE
斗胆提问有关实现的问题

### ISSUE THREAD

**Issue by Bubbleinpit** [yezige/v2ex-issues#1]
敢问阁下的控件是自己手写还是用的哪个库？首页的标签是sticky布局而且可以左右滑动切换，很赞👍。所以想用。因为我用有赞的组件库撸一个小程序(因为这个库好看)，首页也是跟您的v2一样，上面一排标签tab。有赞的tab也支持sticky布局，但是首次滑动会跟随往下滑一下，然后才固定，体验很不好。所以斗胆咨询您的首页tab如何实现的？

**Comment by yezige** [comment]
抱歉最近才看到，我用的小程序的原生组件，上边的是scroll-view，下边是swiper

**Comment by Bubbleinpit** [comment]
感谢，原来是自己写的。
