### ISSUE TITLE
你们的tab切换的时候，原来的内容scroll不会改变

### ISSUE THREAD

**Issue by traceless** [yezige/v2ex-issues#3]
切换tabs 导航栏时候，又倒回去的时候，scroll内容 位置会回到上一页的位置，你们用的是什么UI框架，可以告知下吗，我想用你们的UI框架组件，我也是遇到这个导航栏的问题

**Comment by yezige** [comment]
刚才试了一下，我用的小程序原生的swiper

**Comment by traceless** [comment]
其实也不算BUG，算可以优化的吧。我的是在swiper 里面套了一个scroll, 我下次试试直接用swiper

**Comment by yezige** [comment]
可以贴一下我的代码，里边只是view，我又试了下，切换tabs的时候会自动滚动到顶部（你是希望不回到顶部？）
![image](https://user-images.githubusercontent.com/11436166/76930189-e4fedf80-6920-11ea-83a6-38e2caff45a0.png)

**Comment by yezige** [comment]
鉴于长期无变化，关闭
